name: 'Test Inputs'
description: 'Tests GitHub Actions inputs parsing options'

inputs:
  test-string:
    description: 'Test string input of Actions'
    default: 'Spam Slam'
    required: true

runs:
  env:
    __test_string__: ${{ toJson(inputs.test-string) }}

jobs:
  test-string:
    runs-on: ubuntu-16.04
    steps:
      - name: String Inputs Tests
        run: printf '%s\n' "${__test_string__}"
