name: 'Test Inputs'
description: 'Tests GitHub Actions inputs parsing options'

inputs:
  test-string:
    description: 'Test string input of Actions'
    default: 'Spam Slam'
    required: true

runs:
  env:
    __test_string__: ${{ toJson(inputs.test-string) }}
  using: 'node12'
  main: lib/test-env-inputs.js
