on:
  push:
    branches:
      - master

jobs:
  jekyll_build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source branch for building Pages
        uses: actions/checkout@v1
        with:
          ref: master
          fetch-depth: 10

      - name: Jekyll Build
        uses: gha-utilities/jekyll-build@master
        with:
          # jekyll_github_token: ${{ secrets.JEKYLL_GITHUB_TOKEN }}
          source: ./jekyll-docs
          destination: /var/www/gha-tests

      - name: Checkout branch for GitHub Pages
        uses: actions/checkout@v1
        with:
          ref: gh-pages
          fetch-depth: 1
          submodules: true

      - name: Copy built site files into Git branch
        run: cp -r /var/www/gha-tests ./

      - name: Check if build processes generated anything
        run: ls -ahl ./

      # - name: Open Pull Request
      #   uses: peter-evans/create-pull-request@v1.5.0
      #   env:
      #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      #     COMMIT_MESSAGE: Compiles CSS from SCSS files
      #     PULL_REQUEST_BODY: >
      #       This pull request was auto-generated thanks to [create-pull-request](https://github.com/peter-evans/create-pull-request)
      #
      #       And builds Pages with Jekyll via [scss-utilities/gha-sass](https://github.com/gha-utilities/jekyll-build)

## Thanks_be_to
##   - https://help.github.com/en/articles/contexts-and-expression-syntax-for-github-actions
##   - https://help.github.com/en/articles/metadata-syntax-for-github-actions#inputs
