on: push


jobs:
  one:
    runs-on: ubuntu-16.04
    steps:
      - name: First tests
        # uses: S0AndS0/gha-tests/.github/actions/test-inputs@master
        uses: ${{ github.actor }}/gha-tests/.github/actions/test-inputs@master
        with:
          test_string: 'Ham Fan?'


## Thanks_be_to
##   - https://help.github.com/en/articles/contexts-and-expression-syntax-for-github-actions
##   - https://help.github.com/en/articles/metadata-syntax-for-github-actions#inputs
