on: push



jobs:
  one:
    runs-on: ubuntu-16.04
    steps:
      # - uses: ./.github/actions/test-inputs@master
      - name: First tests
        uses: S0AndS0/gha-tests/.github/actions/test-inputs@master
        # uses: ./.github/actions/test-inputs
        with:
          test-string: 'Ham Fan?'
          ## Lists are not supported with `with` via either of following?
          # test-list: ['first', 2, 'IIV']
          #   - A_One: 'Missed'
          #   - H_Two: 'Hit and Sunk!'
          ## ... Nore are dictionaries...
          # test-dictionary:
          #   first_key: 'Value 1'
          #   second_key: 2


## Thanks_be_to
##   - https://help.github.com/en/articles/contexts-and-expression-syntax-for-github-actions
##   - https://help.github.com/en/articles/metadata-syntax-for-github-actions#inputs
