on: push


jobs:
  build_css:
    runs-on: ubuntu-16.04
    steps:
      - name: Compile main.css from main.scss
        uses: scss-utilities/gha-sass@master
        with:
          repository_name: gha-tests
          sass_source: _scss/main.scss
          sass_destination: assets/css/main.css

## Thanks_be_to
##   - https://help.github.com/en/articles/contexts-and-expression-syntax-for-github-actions
##   - https://help.github.com/en/articles/metadata-syntax-for-github-actions#inputs
