on: push


jobs:
  # build_css:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Compile main.css from main.scss
  #       uses: scss-utilities/gha-sass@master
  #       with:
  #         repository_name: gha-tests
  #         sass_source: _scss/main.scss
  #         sass_destination: assets/css/main.css

  test_docker_node:
    runs-on: ubuntu-latest
    steps:
      - name: Test Node on Docker
        uses: S0AndS0/gha-tests/.github/actions/docker-node@master
        with:
          test_string_one: 'Test string from assigned Actions'
        env:
          test_action_env: 'Test Actions assigning environment variable'


  # open_pull_request:
  #   needs: [build_css]
  #   runs-on: ubuntu-16.04
  #   steps:
  #     - name: Open Pull Request
  #       uses: peter-evans/create-pull-request@v1.5.0
  #       env:
  #         GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  #         COMMIT_MESSAGE: Compiles CSS from SCSS files
  #         PULL_REQUEST_BODY: >
  #           This pull request was auto-generated thanks to [create-pull-request](https://github.com/peter-evans/create-pull-request)
  #
  #           And builds CSS with Dart Sass via [scss-utilities/gha-sass](https://github.com/scss-utilities/gha-sass)

## Thanks_be_to
##   - https://help.github.com/en/articles/contexts-and-expression-syntax-for-github-actions
##   - https://help.github.com/en/articles/metadata-syntax-for-github-actions#inputs
